export const GRADES = [
  { label: "Grade 1", value: "grade_1" },
  { label: "Grade 2", value: "grade_2" },
  { label: "Grade 3", value: "grade_3" },
  { label: "Grade 4", value: "grade_4" },
  { label: "Grade 5", value: "grade_5" },
  { label: "Grade 6", value: "grade_6" },
  { label: "Grade 7", value: "grade_7" },
  { label: "Grade 8", value: "grade_8" },
  { label: "Grade 9", value: "grade_9" },
  { label: "Grade 10", value: "grade_10" },
  { label: "Grade 11", value: "grade_11" },
  { label: "Grade 12", value: "grade_12" },
  {
    label: "Undergraduate - Bachelor's Degree",
    value: "undergraduate_bachelors",
  },
  { label: "Postgraduate - Master's Degree", value: "postgraduate_masters" },
  { label: "Doctorate - PhD", value: "doctorate_phd" },
  { label: "Post-Doctoral", value: "post_doctoral" },
];
